apiVersion: v1
kind: Service
metadata:
  name: nextjs-app-active
  namespace: argocd
spec:
  selector:
    app: nextjs-app
    version: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 32174
  type: NodePort
