name: Main Branch CI

on:
  push:
    branches:
      - main


concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true # Cancel any previous runs in progress

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup and Test
        uses: ./.github/actions/setup-and-test
        with:
          node-version: '16.x'

      - name: Get the current date
        run: echo "CURRENT_DATE=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker image for Main branch
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./DOCKERFILE.web
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/turborepo-github-actions/site:staging-${{ env.CURRENT_DATE }}
            ghcr.io/${{ github.repository_owner }}/turborepo-github-actions/site:sha-${{ github.sha }}
