name: PR Build and Deploy

on:
  pull_request:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup and Test
        uses: ./.github/actions/setup-and-test
        with:
          node-version: '16.x'
      
      - name: Extract PR number
        run: echo "PR_NUMBER=$(echo ${GITHUB_REF#refs/pull/} | cut -d'/' -f1)" >> $GITHUB_ENV
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker image for PR
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./DOCKERFILE.web
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/turborepo-github-actions/site:pr-${{ env.PR_NUMBER }}
          build-args: VERSION=pr-${{ env.PR_NUMBER }}
